version: '3'

services:
  app.prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'prod-pwa-stage'
    image: javi98/vue-quasar-crud-template-prod:1.0.0
    container_name: vue-quasar-crud-template-app-prod
    ports:
      - '85:80'